name: Deploy to Domenomania

on:
  push:
    branches:
      - release_build

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./mybase
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: './mybase/package-lock.json'

      - name: Install dependencies
        run: npm ci --legacy-peer-deps --prefer-offline --no-audit

      - name: Run linting
        run: npm run format:check

      - name: Type check
        run: npm run type-check

      - name: Run Jest unit tests
        run: npm run test:jest

  deploy:
    needs: test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./mybase
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: './mybase/package-lock.json'

      - name: Set up SSH key
        run: |
            mkdir -p ~/.ssh
            echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
            chmod 400 ~/.ssh/id_rsa
            ssh-keyscan dm77338.domenomania.eu >> ~/.ssh/known_hosts

      - name: Clear cache and install dependencies
        run: rm -rf node_modules

      - name: Install dependencies
        run: npm ci --legacy-peer-deps --prefer-offline --no-audit

      - name: Build Angular app
        run: npm run build
        env:
          NODE_ENV: production

      - name: Deploy to Atthost
        run: |
          chmod +x ../deploy.sh
          ../deploy.sh
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }} 