name: Deploy Angular Base to Demo

on:
  push:
    branches:
      - release_build

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: |
          npm cache clean --force
          npm ci --no-audit || npm install --no-audit

      - name: Run linting
        run: npm run lint

      - name: Type check
        run: npm run type-check

      - name: Run Unit tests
        run: npm run test:ci

  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          registry-url: 'https://registry.npmjs.org'
          cache: 'npm'
          cache-dependency-path: 'package-lock.json'

      - name: Set up SSH key
        run: |
            mkdir -p ~/.ssh
            echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
            chmod 400 ~/.ssh/id_rsa
            ssh-keyscan -H dm77338.domenomania.eu >> ~/.ssh/known_hosts
            eval "$(ssh-agent -s)"
            ssh-add ~/.ssh/id_rsa
            echo "SSH agent started and key added"
            
            echo "Private key fingerprint:"
            ssh-keygen -lf ~/.ssh/id_rsa
            
            echo "Testing SSH connection..."
            ssh -o ConnectTimeout=10 dm77338@dm77338.domenomania.eu "echo 'SSH connection successful'"
            
            echo "Trying with verbose output..."
            ssh -v -o ConnectTimeout=10 dm77338@dm77338.domenomania.eu "echo 'SSH connection successful'"

      - name: Clear cache and install dependencies
        run: rm -rf node_modules

      - name: Install dependencies
        run: |
          npm cache clean --force
          npm ci --no-audit || npm install --no-audit

      - name: Build Angular app
        run: npm run build:prod

      - name: Deploy to Demo Hosting
        run: |
          chmod +x deploy.sh
          ./deploy.sh
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_AUTH_SOCK: $SSH_AUTH_SOCK

      - name: Health check
        run: |
          sleep 10
          curl -f https://demo.szwagrzak.pl || exit 1